# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'brightcosmetics' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for brightcosmetics
  pod 'Moltin', '~> 3.0.11'
#  pod 'InstantSearch', '~> 2.0'
#  pod 'AlgoliaSearch-Client-Swift'
  
  target 'brightcosmeticsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'brightcosmeticsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
